services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: ariska-redis
    command: redis-server --requirepass REdis2025!
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD', 'redis-cli', '-a', REDIS_PASSWORD, 'ping' ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - ariskanet

  fastapi:
    build:
      context: .
      dockerfile: .build/api/Dockerfile
    container_name: ariska-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./src/tmp:/app/src/tmp
    networks:
      - ariskanet

  nginx-api:
    image: nginx:alpine
    container_name: ariska-nginx-api
    restart: unless-stopped
    ports:
      - "8999:80"
    volumes:
      - ./.build/nginx/api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - ariskanet
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8999"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build:
      context: .
      dockerfile: .build/app/Dockerfile
    container_name: ariska-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./src/tmp:/app/src/tmp
    depends_on:
      - nginx-api
    networks:
      - ariskanet

  nginx-app:
    image: nginx:alpine
    container_name: ariska-nginx-app
    restart: unless-stopped
    ports:
      - "8555:80"
    volumes:
      - ./.build/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - streamlit
    networks:
      - ariskanet
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8555"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
  tmp:
    driver_opts:
      type: none
      device: ${PWD}/src/tmp
      o: bind

networks:
  ariskanet:
    driver: bridge